let stockProductos = [
    {id: 1, nombre: "Sika Adhesivo de Alta Resistencia Sikaflex 112 Crystal Clear 290ml", tipo: "c", cantidad: 1,  precio: 53.90,  img: './img/Sika Adhesivo de Alta Resistencia Sikaflex 112 Crystal Clear 290ml.jpg'},
    {id: 2, nombre: "Sika Adhesivo para Montaje Sika MaxTak 100ml", tipo: "Adhesivos", cantidad: 1,  precio: 18.90, img: './img/Sika Adhesivo para Montaje Sika MaxTak 100ml.jpg'},
    {id: 3, nombre: "Sika Adhesivo para Montaje Sika MaxTak 300ml", tipo: "Adhesivos", cantidad: 1,  precio: 22.50,img: './img/Sika Adhesivo para Montaje Sika MaxTak 300ml.jpg'},
    {id: 4, nombre: "Sika Adhesivo Transparente Sika MaxTack 300ml", tipo: "Adhesivos", cantidad: 1,  precio: 30.00, img: './img/Sika Adhesivo Transparente Sika MaxTack 300ml.jpg'},
    {id: 5, nombre: "Soldimix Adhesivo extra fuerte 35gr", tipo: "Adhesivos", cantidad: 1,precio: 10.50, img: './img/Soldimix Adhesivo extra fuerte 35gr.jpg'},
    {id: 6, nombre: "Soldimix Adhesivo Moldimix", tipo: "Adhesivos", cantidad: 1, precio: 6.50, img: './img/Soldimix Adhesivo Moldimix.jpg'},
    {id: 7, nombre: "Soldimix Adhesivo Ultra Fuerte 900gr", tipo: "Adhesivos", cantidad: 1,  precio: 129.90,  img: './img/Soldimix Adhesivo Ultra Fuerte 900gr.jpg'},
    {id: 8, nombre: "Soldimix Pegamento Instantáneo 1.5g", tipo: "Adhesivos", cantidad: 1,  precio: 5.50,  img: './img/Soldimix Pegamento Instantáneo 1.5g.jpg'},
    {id: 9, nombre: "Soldimix Soldadura en Frío Ultra Fuerte 65g", tipo: "Adhesivos", cantidad: 1,  precio: 25.00, img: './img/Soldimix Soldadura en Frío Ultra Fuerte 65g.jpg'},
    {id: 10, nombre: "Tekno Adhesivo Enchape Terochap 1gl", tipo: "Adhesivos", cantidad: 1, precio: 75.00, img: './img/Tekno Adhesivo Enchape Terochap 1gl.jpg'},
    {id: 11, nombre: "Tekno Adhesivo Enchape Terochap 5gl", tipo: "Adhesivos", cantidad: 1, precio: 320.00,  img: './img/Tekno Adhesivo Enchape Terochap 5gl.jpg'},
    {id: 12, nombre: "Tekno Adhesivo Sintético Teknocola Clásica 1gl", tipo: "Adhesivos", cantidad: 1,precio: 40.00,  img: './img/Tekno Adhesivo Sintético Teknocola Clásica 1gl.jpg'},
    {id: 13, nombre: "Tekno Adhesivo Sintético Teknocola Extra 1L", tipo: "Adhesivos", cantidad: 1,  precio: 13.00, img: './img/Tekno Adhesivo Sintético Teknocola Extra 1L.jpg'},
    {id: 14, nombre: "Tekno Adhesivo Terokal Record 1gl", tipo: "Adhesivos", cantidad: 1,  precio: 110.00, img: './img/Tekno Adhesivo Terokal Record 1gl.jpg'},
    {id: 15, nombre: "Topex Adhesivo Enchape 1.4gl", tipo: "Adhesivos", cantidad: 1,  precio: 17.50,  img: './img/Topex Adhesivo Enchape 1.4gl.jpg'},
    {id: 16, nombre: "Topex Adhesivo Enchape 1.32gl", tipo: "Adhesivos", cantidad: 1,  precio: 6.90,  img: './img/Topex Adhesivo Enchape 1.32gl.jpg'},
    {id: 17, nombre: "Topex Adhesivo montaje multiuso 100gr", tipo: "Adhesivos", cantidad: 1,  precio: 18.90,  img: './img/Topex Adhesivo montaje multiuso 100gr.jpg'},
    {id: 18, nombre: "Topex Adhesivo Pegalfombras 1.4gl", tipo: "Adhesivos", cantidad: 1,  precio: 27.00,  img: './img/Topex Adhesivo Pegalfombras 1.4gl.jpg'},
    {id: 19, nombre: "Topex Adhesivo Pegatodo 1gl", tipo: "Adhesivos", cantidad: 1,  precio: 63.40,img: './img/Topex Adhesivo Pegatodo 1gl.jpg'},
    {id: 20, nombre: "Uhu Adhesivo de contacto Liquido 33ml", tipo: "Adhesivos", cantidad: 1, precio: 16.30, img: './img/Uhu Adhesivo de contacto Liquido 33ml.jpg'},
    {id: 21, nombre: "Uhu Adhesivo de Montaje Ultra Fuerte 100gr", tipo: "Adhesivos", cantidad: 1,  precio: 28.00,img: './img/Uhu Adhesivo de Montaje Ultra Fuerte 100gr.jpg'},
    {id: 22, nombre: "Uhu Adhesivo epóxico Ultra Fuerte 14ml", tipo: "Adhesivos", cantidad: 1,  precio: 25.90, img: './img/Uhu Adhesivo epóxico Ultra Fuerte 14ml.jpg'},
    {id: 23, nombre: "Uhu Adhesivo Multiuso 35ml", tipo: "Adhesivos", cantidad: 1, precio: 14.00,img: './img/Uhu Adhesivo Multiuso 35ml.jpg'},
    {id: 24, nombre: "Uhu Adhesivo Multiuso 60ml", tipo: "Adhesivos", cantidad: 1,  precio: 12.00,  img: './img/Uhu Adhesivo Multiuso 60mljpg'},
]